---
title: "Eg_Selenge Fish Movements"
author: "J.Hart"
date: "2025-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Attach packages}
# Attach packages

#install.packages("pacman")
library(pacman)

pacman::p_load(tidyverse, sf, readxl, riverdist, janitor, maptiles, tidyterra, ggpattern, lubridate, ggtext)
```

```{r Read in data}

# Read in all fish movements 
allfish <- read_csv("Final Data Sheets/All Fish Movements_Eg_Selenge.csv")%>% 
  clean_names() %>% 
  mutate(date = mdy_hm(date)) # convert to date type

# Filter for only taimen observations & > 1 location acquisitions
taimen <- allfish %>%
  filter(species == "Taimen") %>% 
  group_by(fish_id) %>%
  filter(n() > 1) %>%
  ungroup()

```

```{r Calculate # of geolocations and months range}

# Number of geolocations per fish (filter out only 1 geolocation)
numb_geolocations <- allfish %>% 
  group_by(fish_id) %>% 
  summarize(count = n()) %>% 
  filter(count > 1) %>% 
  rename(id = fish_id)

# Number of months between first and last geolocation
months_range <- allfish %>% 
  group_by(fish_id) %>% 
  filter(n() > 1) %>%
  rename(id = fish_id) %>% 
  arrange(id, date) %>% 
  summarize(min_date = min(date),
            max_date = max(date)) %>% 
  mutate(days = interval(min_date, max_date) %/% days (1)) %>% 
  mutate(partial_months = round(days / (365/12), digits = 1),
         whole_months = round(partial_months, digits = 0))
```

```{r Read in data as spatial object and map}

# Convert all fish movements to sf object and project to UTM
allfish_sf <- st_as_sf(allfish, coords = c("long_map_adjusted", "lat_map_adjusted")) %>%
  st_set_crs(4326) %>% 
  st_transform(crs = 32648) # Project WGS84 UTM Zone 48N


# Convert taimen movements to sf object and project to UTM
taimen_sf <- st_as_sf(taimen, coords = c("long_map_adjusted", "lat_map_adjusted")) %>%
  st_set_crs(4326) %>% 
  st_transform(crs = 32648) # Project WGS84 UTM Zone 48N

# Get basemap tiles for reference
tiles <- get_tiles(taimen_sf, provider = "OpenStreetMap", crop=FALSE)
#plot_tiles(tiles)

# Plot taimen locations for visual check
ggplot() +
  geom_spatraster_rgb(data = tiles) +
  geom_sf(data = taimen_sf, color = "blue") +
  labs(title = "Taimen Movement Locations - Eg/Selenge") +
  theme_minimal()


```

```{r Load river network}
# Load river network
MyRivernetwork <- line2network(path ="Spatial", layer ="FlowNetwork_Final")

# Confirm river network looks accurate
plot(MyRivernetwork)

# Show network segments
showends(seg=1, rivers=MyRivernetwork)
showends(seg=2, rivers=MyRivernetwork)

# Define start of river network
riv <- setmouth(seg=1,vert=22362,rivers=MyRivernetwork)
plot(riv)

# Run and perform topology checks on river network
network_clean <- cleanup(riv)

# Verify river network segmented correctly
topologydots(rivers=network_clean)


```

```{r Calculate distances}

## Euclidean Distances

# Find max euclidean distance
euc_distances <- taimen_sf %>%
  group_by(fish_id) %>% 
  summarize(
    max_dist_m = max(st_distance(geometry, geometry)))

#-----------------------------------------------

## River Distances

# Create vector of fish ID's to loop through
id_vec <- unique(taimen$fish_id)

# Create empty data frame for max displacement results
max_river_distance <- data.frame(id = character(), max_river_distance_km = numeric(), stringsAsFactors = FALSE)

# Calculate max displacement 
for (i in id_vec) {
  taimen_locs <- pointshp2segvert(path ="Spatial", layer ="Taimen", rivers=network_clean) %>% 
  filter(Code == i) #  Snap point locations to cleaned river network
  
  distance_matrix <- riverdistancemat(seg = taimen_locs$seg, vert = taimen_locs$vert, rivers = network_clean) # Calculate distances between each location ping 
  max_distance_km <- max(distance_matrix) / 1000 # Calculate max river distance in km
  new_row <- data.frame(id = paste(i), max_river_distance_km = max_distance_km) 
  max_river_distance <- rbind(max_river_distance, new_row) # Append to results table
  
}
  

# View point locations on network
zoomtoseg(seg=1, rivers=network_clean)
points(taimen_locs$snap_x, taimen_locs$snap_y, pch=16, col="red")
riverpoints(seg=taimen_locs$seg, vert=taimen_locs$vert, rivers=network_clean, pch=15, col="blue")

```

```{r max displacement plot}

# Fish that swam between proposed Eg hydro project site
crossed_dam_site <- c("102", "152", "153", "154", "159")

max_river_distance <- max_river_distance %>% 
  mutate(crossed_dam = ifelse(id %in% crossed_dam_site, "Yes", "No"))


# Create max displacement plot
ggplot(max_river_distance, aes(x = reorder(as.factor(id),max_river_distance_km), y = max_river_distance_km, fill = crossed_dam)) +
  geom_col() +
  scale_fill_manual(values = c("deepskyblue3", "coral2")) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 260)) +
  labs(title = "Taimen Tracking Maximum Displacement",
       subtitle = "Selenge/Eg Rivers",
       y = "River KM",
       x = "Taimen Tag ID",
       fill = "Crossed Proposed Egiin Gol Hydroelectric Site") +
  theme_bw() +
  theme(legend.position = "bottom",
        plot.subtitle = element_text(size = 14),
        plot.title = element_text(size= 16, face="bold"),
        axis.text=element_text(size= 10),
        axis.title=element_text(size= 12)) 


#ggsave(filename = "Taimen_MaxDisplacement_Plot.png", height = 6, width = 8)
```

```{r Home range}
# Calculating observed minimum home range for all individuals

taimen_locs <- pointshp2segvert(path ="Spatial", layer ="Taimen", rivers=network_clean) 

# Minimum home range (m)
par(mfrow=c(1,2))
ranges <- homerange(unique=taimen_locs$Code, seg=taimen_locs$seg, vert=taimen_locs$vert, rivers=network_clean)

# Plot home range
plot(ranges, cumulative=TRUE, label=TRUE)

```

```{r Date seq distances}
## Distance between locations pings - date sequence

# Filter for unique ID of interest
taimen_locs <- pointshp2segvert(path ="Spatial", layer ="Taimen", rivers=network_clean) %>% 
  filter(Code == 104) %>% 
  arrange(Code, Date) 

# Calculate sequential date distances
distance_dateseq <- riverdistanceseq(unique=taimen_locs$Code, survey=taimen_locs$Survey,
      seg=taimen_locs$seg, vert=taimen_locs$vert, rivers=network_clean) %>% 
      pivot_longer( 
             cols = everything(),
             names_to = "date",
             values_to = "distance") %>% 
      mutate(dist_km = distance / 1000)

# Plot
labels <- taimen_locs$Date[-1]

ggplot(distance_dateseq, aes(x = as.factor(date), y = dist_km, group = 1)) + 
  geom_path(linewidth = 1) +
  scale_x_discrete(labels = labels) +
  labs(x = "Date",
       y = "Distance (km)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r All fish plot movements}
## All fish movement plot

# Filter for >1 location acquistions
allfish <- read.csv("Final Data Sheets/All Fish Movements_Eg_Selenge.csv") %>% 
  clean_names() %>% 
  group_by(fish_id) %>%
  filter(n() > 1) %>%
  ungroup()

# Unique id labels
id_vec <- unique(allfish$fish_id)

# Create empty data frame for max displacement results
max_river_distance_all <- data.frame(id = character(), max_river_distance_km = numeric(), stringsAsFactors = FALSE)


# Calculate max displacement 
for (i in id_vec) {
  allfish_locs <- pointshp2segvert(path ="Spatial", layer ="AllFish", rivers=network_clean) %>% 
    filter(Code == i)
  distance_matrix <- riverdistancemat(seg =  allfish_locs$seg, vert =  allfish_locs$vert, rivers = network_clean) # Calculate distances between each location ping 
  max_distance_km <- max(distance_matrix) / 1000 # Calculate max river distance in km
  new_row <- data.frame(id = paste(i), max_river_distance_km = max_distance_km) 
  max_river_distance_all <- rbind(max_river_distance_all, new_row) # Append to results table
  }

max_river_distance_all <- max_river_distance_all %>% 
  mutate(crossed_dam = ifelse(id %in% crossed_dam_site, "Yes", "No"))

```


```{r All fish max displacement plot}
# Read in all fish plot data and append geolocation count and date range
allfish_plotdata <- read_csv("Final Data Sheets/max_river_distance_allfish.csv") %>% 
  cbind(numb_geolocations$count, months_range$whole_months) 

# Create color vector for different species
species <- c("Taimen", "Pike", "White Fish", "Lenok", "Perch")
species_colors <- c("Taimen" = "olivedrab", "Pike" = "darkred", "White Fish" = "burlywood4", "Lenok" = "darkorange", "Perch" = "darkblue")


# Create look up table to assign colors to fish id's in x-axis labels
tag_ids <- levels(reorder(as.factor(allfish_plotdata$id), allfish_plotdata$max_river_distance_km))
id2species <- setNames(allfish_plotdata$species, as.character(allfish_plotdata$id))
id2color <- species_colors[id2species[tag_ids]]
id_labels <- setNames(
  paste0("<span style='color:", id2color, "'>", tag_ids, "</span>"),
  tag_ids
)


# Create max displacement plot
ggplot(allfish_plotdata, aes(x = reorder(as.factor(id),max_river_distance_km), 
                             y = max_river_distance_km, 
                             fill = species, 
                             pattern = crossed_dam)) +
  geom_col_pattern(linewidth=0.7, 
                   color = "black",
                   pattern_spacing = 0.025,
                   pattern_fill = "white",  
                   pattern_density = 0.3) +
  scale_pattern_manual(values = c("Yes" = "stripe", "No" = "none")) +
  scale_fill_manual(values = species_colors) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 280), breaks = seq(0,250, by=50)) +
  scale_x_discrete(labels = id_labels) +
  labs(#title = "Fish Tracking Maximum Displacement",
       #subtitle = "Selenge/Eg Rivers",
       y = "**River Distance (km)**",
       x = "**Fish Tag ID**",
       pattern = "Crossed Proposed Egiin Gol Hydroelectric Site:",
       fill = "Species:") +
  geom_text(aes(label = paste0("(",months_range$partial_months,")"), color = species), 
            vjust = -0.5,
            size = 3.5,
            fontface = "bold",
            show.legend = FALSE) +
  geom_text(aes(label = numb_geolocations$count, color = species), 
            vjust = -2, 
            fontface = "bold",
            size = 4,
            show.legend = FALSE) +
 scale_color_manual(values = species_colors) +
 annotate("curve", 
           x = 16.5, y = 170, 
           xend = 18.4, yend = 162, 
           arrow = arrow(length = unit(0.3, "cm"), type = "closed"), 
           curvature = 0.1, # Adjust the curve direction and strength
           color = "black", 
           linewidth = 1) +
 annotate("curve", 
           x = 16.5, y = 195, 
           xend = 18.7, yend = 175, 
           arrow = arrow(length = unit(0.3, "cm"), type = "closed"), 
           curvature = 0.2, # Adjust the curve direction and strength
           color = "black", 
           linewidth = 1) +
 annotate("text", x = 14.6, y = 173, label = "Months Elapsed", color = "black", size = 5) +
 annotate("text", x = 14.5, y = 197, label = "# of Geolocations", color = "black", size = 5) +
  theme_bw() +
  theme(legend.position = "bottom",
        plot.subtitle = element_text(size = 16),
        plot.title = element_text(size= 18, face="bold"),
        axis.text=element_text(size= 13),
        axis.title=element_text(size= 14),
        axis.title.x = element_markdown(),
        axis.title.y = element_markdown(),
        axis.text.x = element_markdown(angle = 45, 
                                   hjust = 1)) +
        guides(fill = guide_legend(override.aes = list(pattern = "none")),
               pattern = guide_legend(override.aes = list(
                 pattern_density = 0.2, 
                 pattern_spacing = 0.015,
                 fill = 'white')))

 ggsave(filename = "Plots/AllFish_MaxDisplacement_Plot_Annotated.png", height = 6, width = 12)
```

